
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


